# ########## API Documentation ##########

### Tasks #####
#### Get all tasks
GET http://localhost:3000/Tasks
Accept: application/json

### 

#### Create a new task
POST http://localhost:3000/Tasks
Content-Type: application/json

{
    "title": "Walk the dog",
    "date": "2024-10-28",
    "due_date": "2024-11-05",
    "location": "The park",
    "subtasks": ["Put on the leash", "Bring poop bags"],
    "category": "Pet",
    "completed": false
}

### Render

Get 




### 

### HolidayTasks ##### 

#### Get all holiday tasks
GET http://localhost:3000/HolidayTasks
Accept: application/json

### 

#### Create a new holiday task
POST http://localhost:3000/HolidayTasks
Content-Type: application/json

{
    "title": "Buy Girls toys",
    "date": "2024-10-27",
    "location": "The Mall",
    "subtasks": ["Buy dolls", "Buy dresses"],
    "gifts": [],
    "task_for_who": ["Daughter"],
    "category": "Birthday",
    "completed": false
}

### Render 
