# ########## API Documentation ##########

### Tasks #####
#### Get all tasks
GET http://localhost:3000/Tasks
Accept: application/json

### 

#### Create a new task
POST http://localhost:3000/Tasks
Content-Type: application/json

{
    "title": "Walk the horse",
    "date": "2024-10-28",
    "due_date": "2024-11-05",
    "location": "The park",
    "subtasks": ["Put on the leash", "Bring poop bags"],
    "category": "Pet",
    "completed": false
}

###
PUT http://localhost:3000/Tasks/6745d0b1cba34d78c381799f
Content-Type: application/json

{
    "title": "Butcher the horse",
    "date": "2024-10-28",
    "due_date": "2024-11-05",
    "location": "The butcher",
    "subtasks": ["Cut the meat", "Pack the meat"],
    "category": "Meat",
    "completed": false
}

###
DELETE http://localhost:3000/Tasks/6745d0cecba34d78c38179a1
Accept: application/json

{
    "delete": "true"
}

### Render

Get 




### 

### HolidayTasks ##### 

#### Get all holiday tasks
GET http://localhost:3000/HolidayTasks
Accept: application/json

### 

#### Create a new holiday task
POST http://localhost:3000/HolidayTasks
Content-Type: application/json

{
    "title": "Buy Girls toys",
    "date": "2024-10-27",
    "location": "The Mall",
    "subtasks": ["Buy dolls", "Buy dresses"],
    "gifts": [],
    "task_for_who": ["Daughter"],
    "category": "Birthday",
    "completed": false
}

###
PUT http://localhost:3000/HolidayTasks/671ff7c6f35ebd8f85fbc1e0
Content-Type: application/json

{
    "title": "Buy Boy toys",
    "date": "2024-10-27",
    "location": "The Mall",
    "subtasks": ["Buy Bikes", "Buy Jacks"],
    "gifts": [],
    "task_for_who": ["Daughter"],
    "category": "Birthday",
    "completed": false
}

### 

DELETE http://localhost:3000/HolidayTasks/67269a26235b00536e0be5df
Accept: application/json

{
    "delete": "true"
}

### Render 
